AX_ALT_SHIFT_M = [ "KBD_SHIFT_LT_PRS", "KBD_M_PRS", "KBD_M_RLS", "KBD_SHIFT_LT_RLS", "SYN_REPORT",]
AX_CTRL_Q = [ "KBD_CTRL_LT_PRS", "KBD_Q_PRS", "KBD_Q_RLS", "KBD_CTRL_LT_RLS", "SYN_REPORT",]
AX_F5 = [ [ "KBD_F5_PRS", "KBD_F5_RLS", "SYN_REPORT",], [ "KBD_ENTER_PRS", "KBD_ENTER_RLS", "SYN_REPORT",],]
AX_F6 = [ [ "KBD_F6_PRS", "KBD_F6_RLS", "SYN_REPORT",], [ "KBD_ENTER_PRS", "KBD_ENTER_RLS", "SYN_REPORT",],]
