[K_SHANWAN.GB_01]
K_ACTIONS = "AX_ALT_SHIFT_M↔AX_CTRL_S↕AX_CTRL_Q"
K_DESCRIPTION = "Mirror in many apps."
K_INDEX = 0
K_MODE = "KM_SEQUENCE"
K_PAUSE = "KP_NONE"
K_REPEAT = "KR_NONE"

[K_SHANWAN."GB_05.GB_06.GB_01"]
K_ACTIONS = "AX_CTRL_Q"
K_DESCRIPTION = "Often quit."
K_INDEX = 0
K_MODE = "KM_NORMAL"
K_PAUSE = "KP_NONE"
K_REPEAT = "KR_NONE"

[K_SHANWAN."GB_06.GB_09"]
K_ACTIONS = "AX_F5_COPY"
K_DESCRIPTION = "Press F5, then enter."
K_INDEX = 0
K_MODE = "KM_SEQUENCE"
K_PAUSE = "KP_ZERO"
K_REPEAT = "KR_NONE"

[K_SHANWAN."GB_05.GB_09"]
K_ACTIONS = "AX_F6_MOVE"
K_DESCRIPTION = "Press F6, then enter."
K_INDEX = 0
K_MODE = "KM_SEQUENCE"
K_PAUSE = "KP_ZERO"
K_REPEAT = "KR_NONE"
